// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import "../styles/theme.css"; // <-- adicionamos essa linha
import "../lib/fonts";
import { AuthProvider } from "@/contexts/AuthContext";
import { Navbar } from "@/components/custom/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bem Concreto Token - BCT",
  description: "Plataforma de compra e venda de tokens BCT com PIX e cartão",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased font-inter bg-[#0D0F11] text-[#F2F2F2]`}
      >
        <AuthProvider>
          <Navbar />
          <main className="min-h-screen px-4 md:px-8 py-6 bg-[#0D0F11]">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
